# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 19:38
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=128)),
                ('ip', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.SmallIntegerField(choices=[(1, 'LSA'), (2, 'Sphinx')])),
                ('relevance', models.SmallIntegerField(choices=[(0, 'Не релевантный'), (1, 'Немного соответсвует запросу'), (2, 'По большей степени соответствует запросу'), (3, 'Совершенно релевантный')])),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.Document')),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.SearchQuery')),
            ],
        ),
    ]
