# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0002_auto_20160513_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='position',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
