# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0003_searchresult_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='web_site.DocumentGroup'),
        ),
    ]
