# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0004_auto_20160518_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='ideal_dcg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='ideal_strong_avg_prec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='ideal_strong_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='ideal_weak_avg_prec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='ideal_weak_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='lsa_dcg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='lsa_strong_avg_prec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='lsa_strong_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='lsa_weak_avg_prec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='lsa_weak_precision',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
