# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0006_auto_20160519_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='ideal_strong_reciprocal_rank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='ideal_weak_reciprocal_rank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='lsa_strong_reciprocal_rank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='lsa_weak_reciprocal_rank',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
